import Head from "next/head";
import Image from "next/image";

import FullCalendar from "@fullcalendar/react";
import interactionPlugin from "@fullcalendar/interaction";
import timeGridPlugin from "@fullcalendar/timegrid";

import "@fullcalendar/common/main.css";
import "@fullcalendar/daygrid/main.css";
import "@fullcalendar/timegrid/main.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Next.js FullCalendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FullCalendar
        plugins={[interactionPlugin, timeGridPlugin]}
        initialView="timeGridWeek"
        nowIndicator={true}
        editable={true}
        initialEvents={[{ title: "Initial event", start: new Date() }]}
      />
    </div>
  );
}
